<?php
/** @var \Ubermanu\CookieConsent\Block\CookieConsent $block */
?>
<?php if ($block->isEnabled()): ?>
    <style>
        @import "https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@v2.8.6/dist/cookieconsent.css";
    </style>
    <script>
        require([
            'Ubermanu_CookieConsent/js/cookie-consent',
            'domReady!'
        ], function (cookieConsent) {
            'use strict';
            cookieConsent.run(<?= $block->getJsLayout() ?>);
        });
    </script>
<?php endif; ?>
