<?php
/** @var \Ubermanu\CookieConsent\Block\CookieConsent $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php if ($block->isEnabled()): ?>
    <?php
    $cookieConsentConfig = $block->getJsLayout();
    $scriptString = "
        require([
            'Ubermanu_CookieConsent/js/cookie-consent',
            'domReady!'
        ], function (cookieConsent) {
            'use strict';
            cookieConsent().run($cookieConsentConfig);
        });";
    ?>
    <?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
